# Generated by Django 5.2.6 on 2025-09-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="col_max",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="row_max",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
