# Generated by Django 5.2.6 on 2025-09-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_room_col_max_alter_room_row_max"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="col_max",
        ),
        migrations.RemoveField(
            model_name="room",
            name="row_max",
        ),
    ]
