# Generated by Django 5.2.6 on 2025-09-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_remove_room_col_max_remove_room_row_max"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("screening", "seats")},
        ),
    ]
