# Generated by Django 5.2.6 on 2025-09-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_reservation_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screening",
            name="start_time",
            field=models.DateTimeField(null=True),
        ),
    ]
